# SPDX-License-Identifier: Apache-2.0
"""Remote direct-fill control protocol and hardware-independent state core."""

# First Party
from lmcache.v1.remote_fill_diagnostics import (
    REMOTE_FILL_DIAGNOSTIC_MARKER,
    REMOTE_FILL_VALIDATION_MARKER,
    log_remote_fill_diagnostic,
    log_remote_fill_validation_failure,
)

# Local
from .codec import (
    ProtocolValidationError,
    decode_request,
    decode_response,
    encode_request,
    encode_response,
    validate_request,
)
from .native import (
    DIRECT_PUSH_H0_QUALIFICATION_V1,
    DirectPushPageSource,
    DirectPushSourcePlan,
    NativeDirectPushActivation,
    NativeDirectPushAmbiguousError,
    NativeDirectPushPreSubmitError,
    NativeDirectPushResult,
    NativeDirectPushTerminalError,
)
from .protocol import (
    PROTOCOL_VERSION,
    AbortRequest,
    ArmWindowRequest,
    ControlPage,
    DestinationNativeState,
    DestinationPageDescriptor,
    FinishRequest,
    NegotiateRequest,
    OpenRequest,
    OperationIdentity,
    OperationKind,
    PageDisposition,
    PagePreparationStatus,
    ProtocolLimits,
    RemoteFillRequest,
    RemoteFillResponse,
    ReportTransferCompleteRequest,
    ReserveWindowRequest,
    ResultCode,
    StatusRequest,
    TerminalOutcome,
    TransactionState,
    WindowState,
    WindowStatus,
)
from .security import (
    content_digest,
    descriptor_capability_mac,
    destination_descriptor_digest,
    manifest_digest,
    request_payload_digest,
    seal_descriptor,
    seal_request,
    transaction_manifest_digest,
    verify_descriptor,
)
from .service import RemoteFillService
from .state import (
    AllocatedPage,
    NegotiationSpec,
    PageLifecycle,
    PreparedPage,
    RemoteFillMetricsSnapshot,
    RemoteFillStateCore,
    ReservedPageView,
    UnsafePageLifecycleError,
)
from .transport import (
    REMOTE_FILL_ENVELOPE_VERSION,
    REMOTE_FILL_SERVICE_HEADER,
    ByteRoundTripTransport,
    InProcessRemoteFillTransport,
    RemoteFillClient,
    RemoteFillRpcServer,
    RemoteFillTransportError,
    ReplyLostError,
    RpcRemoteFillByteTransport,
)

__all__ = [
    "PROTOCOL_VERSION",
    "REMOTE_FILL_ENVELOPE_VERSION",
    "REMOTE_FILL_DIAGNOSTIC_MARKER",
    "REMOTE_FILL_SERVICE_HEADER",
    "REMOTE_FILL_VALIDATION_MARKER",
    "AbortRequest",
    "AllocatedPage",
    "ArmWindowRequest",
    "ByteRoundTripTransport",
    "ControlPage",
    "DIRECT_PUSH_H0_QUALIFICATION_V1",
    "DestinationNativeState",
    "DestinationPageDescriptor",
    "DirectPushPageSource",
    "DirectPushSourcePlan",
    "FinishRequest",
    "InProcessRemoteFillTransport",
    "NegotiateRequest",
    "NegotiationSpec",
    "NativeDirectPushActivation",
    "NativeDirectPushAmbiguousError",
    "NativeDirectPushPreSubmitError",
    "NativeDirectPushResult",
    "NativeDirectPushTerminalError",
    "OpenRequest",
    "OperationIdentity",
    "OperationKind",
    "PageDisposition",
    "PageLifecycle",
    "PagePreparationStatus",
    "PreparedPage",
    "ProtocolLimits",
    "ProtocolValidationError",
    "RemoteFillClient",
    "RemoteFillMetricsSnapshot",
    "RemoteFillRequest",
    "RemoteFillResponse",
    "RemoteFillRpcServer",
    "RemoteFillService",
    "RemoteFillStateCore",
    "RemoteFillTransportError",
    "ReplyLostError",
    "ReportTransferCompleteRequest",
    "ReserveWindowRequest",
    "ReservedPageView",
    "UnsafePageLifecycleError",
    "ResultCode",
    "RpcRemoteFillByteTransport",
    "StatusRequest",
    "TerminalOutcome",
    "TransactionState",
    "WindowState",
    "WindowStatus",
    "content_digest",
    "decode_request",
    "decode_response",
    "descriptor_capability_mac",
    "destination_descriptor_digest",
    "encode_request",
    "encode_response",
    "manifest_digest",
    "log_remote_fill_diagnostic",
    "log_remote_fill_validation_failure",
    "request_payload_digest",
    "seal_descriptor",
    "seal_request",
    "transaction_manifest_digest",
    "validate_request",
    "verify_descriptor",
]
